# Generated by Django 5.0.6 on 2024-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_fiedl',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
