# Generated by Django 5.0.6 on 2024-12-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='profile_image',
            field=models.ImageField(default='user_profile/default.png', upload_to='user_profile'),
        ),
    ]
