# Generated by Django 5.0.6 on 2025-01-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bloger_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
